
interface latch {
    use wasi:http/types@0.3.0.{error-code as http-error-code, request};

    record send-args {
        request: borrow<request>,
    }

    record handle-args {
        request: borrow<request>,
    }

    variant client-operation {
        send(send-args),
    }

    variant handler-operation {
        handle(handle-args),
    }

    variant operation {
        client(client-operation),
        handler(handler-operation),
    }

    variant decision {
        abstained,
        denied(http-error-code),
    }

    variant error-code {
        http(http-error-code),
        other(option<string>),
    }

    authorize: func(operation: operation) -> result<decision, error-code>;
}

interface latch0 {
    use latch.{operation, decision, error-code};

    authorize: func(operation: operation) -> result<decision, error-code>;
}

interface latch1 {
    use latch.{operation, decision, error-code};

    authorize: func(operation: operation) -> result<decision, error-code>;
}

interface latch2 {
    use latch.{operation, decision, error-code};

    authorize: func(operation: operation) -> result<decision, error-code>;
}

interface latch3 {
    use latch.{operation, decision, error-code};

    authorize: func(operation: operation) -> result<decision, error-code>;
}

interface latch4 {
    use latch.{operation, decision, error-code};

    authorize: func(operation: operation) -> result<decision, error-code>;
}
